name: Release

on:
  push:
    branches:
    - main
  release:
    types:
    - published

jobs:
  publish_image:
    name: Publish image
    uses: OpenTTD/actions/.github/workflows/publish-image.yml@v3

  deploy:
    name: Deploy
    needs:
    - publish_image

    uses: ./.github/workflows/deploy-aws.yml
    with:
      is_staging: ${{ github.ref == 'refs/heads/main' }}
      name: Relay
      cluster: Relay
      digest: ${{ needs.publish_image.outputs.digest }}
      version: ${{ needs.publish_image.outputs.version }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
